# Generated by Django 6.0.4 on 2026-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'genai'", max_length=60, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in sidebar (low = first)')),
                ('icon_name', models.CharField(help_text="Lucide icon name used by the frontend, e.g. 'Brain', 'Globe', 'Database'", max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('duration', models.CharField(help_text="e.g. '12 Weeks'", max_length=60)),
                ('format', models.CharField(help_text="e.g. 'Live + Project'", max_length=80)),
                ('has_internship', models.BooleanField(default=False)),
                ('has_certificate', models.BooleanField(default=True)),
                ('tagline', models.CharField(max_length=220)),
                ('overview', models.TextField()),
                ('modules', models.JSONField(default=list, help_text='Array of {title, topics[]} objects')),
                ('tools', models.JSONField(default=list, help_text='Array of tool/stack name strings')),
                ('is_active', models.BooleanField(default=True, help_text="Hidden programs won't appear in the API")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
