# Generated by Django 6.0.4 on 2026-05-26 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_recordcand_certificate_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('resume', models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('budget', models.CharField(blank=True, max_length=60)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='quote_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='recordcand',
            name='duration',
            field=models.CharField(blank=True, default='', help_text='e.g. 3 months, 12 weeks', max_length=80),
        ),
        migrations.AddField(
            model_name='recordcand',
            name='projects',
            field=models.JSONField(blank=True, help_text='Optional list of project objects, e.g. [{"title": "...", "description": "..."}]', null=True),
        ),
    ]
