# Generated by Django 6.0.4 on 2026-07-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_hiringapplication_quoterequest_blogpost_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlaceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=100, unique=True)),
                ('rating_value', models.FloatField(default=5.0)),
                ('review_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Place Rating',
                'verbose_name_plural': 'Google Place Ratings',
            },
        ),
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=5.0)),
                ('text', models.TextField(blank=True)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dashboard.googleplacerating')),
            ],
            options={
                'verbose_name': 'Google Review',
                'verbose_name_plural': 'Google Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
